#!/usr/bin/bash

PATH_DATA_FILE="$HOME/.local/bin/PATH_DATA.txt";
BM_DATA_FILE="$HOME/.local/bin/BM_DATA.txt";

PATH_DATA=$(cat $PATH_DATA_FILE); 
BM_DATA=$(cat $BM_DATA_FILE);

n=1;

INPT=$1;
BOOK_MARK=${INPT%%/*};
EXTND_PATH=${INPT#*/};

if [[ $INPT == 'new' ]]; then

    echo 'new book-mark set';
    echo $2 >> $BM_DATA_FILE;
    echo $(pwd) >> $PATH_DATA_FILE;

elif [[ $INPT == 'ls' ]]; then
    
    for i in ${BM_DATA[@]}; do
        echo $i $(cat $PATH_DATA_FILE | sed -n ''$n'p');
        n=$((n+1));
    done

elif [[ $INPT == 'rm' ]]; then
    
    lineNumber=$(sed -n "/$2/{=;d}" $BM_DATA_FILE);
    sed -i ''$lineNumber'd' $BM_DATA_FILE;
    sed -i ''$lineNumber'd' $PATH_DATA_FILE;

else
    
    lineNumber=$(sed -n "/$BOOK_MARK/{=;d}" $BM_DATA_FILE);
    cd $(sed -n ''$lineNumber'p' $PATH_DATA_FILE);
    if [[ $EXTND_PATH != $INPT ]]; then
        cd $EXTND_PATH;
    fi

fi

